/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_v1_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Data */
        get: operations["map_data_api_v1_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competitive */
        get: operations["competitive_api_v1_competitive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Area */
        Area: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Value */
            value: number | null;
            /** Closed Sales */
            closed_sales: number;
            /** Median Price */
            median_price: number | null;
        };
        /** Cell */
        Cell: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Count */
            count: number;
        };
        /** Competitive */
        Competitive: {
            meta: components["schemas"]["Meta"];
            /** Agents */
            agents: components["schemas"]["Entity"][];
            /** Offices */
            offices: components["schemas"]["Entity"][];
            /** Closed Sales */
            closed_sales: number;
            /** Sales Volume */
            sales_volume: number;
        };
        /** Entity */
        Entity: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Closed Sales */
            closed_sales: number;
            /** Sales Volume */
            sales_volume: number;
            /** Median Price */
            median_price: number | null;
            /** Market Share */
            market_share: number;
        };
        /** FilterOptions */
        FilterOptions: {
            meta: components["schemas"]["Meta"];
            /** Counties */
            counties: string[];
            /** Cities */
            cities: string[];
            /** Zips */
            zips: string[];
            /** Subtypes */
            subtypes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MapData */
        MapData: {
            meta: components["schemas"]["Meta"];
            /**
             * Metric
             * @enum {string}
             */
            metric: "median_price" | "closed_sales" | "concentration";
            /**
             * Level
             * @enum {string}
             */
            level: "county" | "zip";
            /** Areas */
            areas: components["schemas"]["Area"][];
            /** Cells */
            cells: components["schemas"]["Cell"][];
            /** Unmapped Sales */
            unmapped_sales: number;
        };
        /** Meta */
        Meta: {
            /** Version */
            version: string;
            /** Start Month */
            start_month: string;
            /** End Month */
            end_month: string;
            /** Published At */
            published_at: string;
            /** Demo */
            demo: boolean;
            /** Months */
            months: string[];
            /**
             * Source
             * @default CRMLS via Trestle
             */
            source: string;
            /** Units */
            units?: {
                [key: string]: string;
            };
            /**
             * Refresh Schedule
             * @default Monthly · day 7 · 6:00 AM Pacific
             */
            refresh_schedule: string;
        };
        /** Metrics */
        Metrics: {
            /**
             * New Listings
             * @default 0
             */
            new_listings: number;
            /**
             * Closed Sales
             * @default 0
             */
            closed_sales: number;
            /** Median Price */
            median_price?: number | null;
            /** Days On Market */
            days_on_market?: number | null;
            /** Price Sqft */
            price_sqft?: number | null;
            /** Price Ratio */
            price_ratio?: number | null;
            /** Mortgage Rate */
            mortgage_rate?: number | null;
            /**
             * Days Sample
             * @default 0
             */
            days_sample: number;
            /**
             * Sqft Sample
             * @default 0
             */
            sqft_sample: number;
            /**
             * Ratio Sample
             * @default 0
             */
            ratio_sample: number;
        };
        /** Summary */
        Summary: {
            meta: components["schemas"]["Meta"];
            /** Month */
            month: string;
            current: components["schemas"]["Metrics"];
            previous: components["schemas"]["Metrics"] | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * New Listings
             * @default 0
             */
            new_listings: number;
            /**
             * Closed Sales
             * @default 0
             */
            closed_sales: number;
            /** Median Price */
            median_price?: number | null;
            /** Days On Market */
            days_on_market?: number | null;
            /** Price Sqft */
            price_sqft?: number | null;
            /** Price Ratio */
            price_ratio?: number | null;
            /** Mortgage Rate */
            mortgage_rate?: number | null;
            /**
             * Days Sample
             * @default 0
             */
            days_sample: number;
            /**
             * Sqft Sample
             * @default 0
             */
            sqft_sample: number;
            /**
             * Ratio Sample
             * @default 0
             */
            ratio_sample: number;
            /** Month */
            month: string;
        };
        /** Trends */
        Trends: {
            meta: components["schemas"]["Meta"];
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    filters_api_v1_filters_get: {
        parameters: {
            query?: {
                version?: string | null;
                month?: string | null;
                county?: string | null;
                city?: string | null;
                zip?: string | null;
                subtype?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_summary_get: {
        parameters: {
            query?: {
                version?: string | null;
                month?: string | null;
                county?: string | null;
                city?: string | null;
                zip?: string | null;
                subtype?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_v1_trends_get: {
        parameters: {
            query?: {
                version?: string | null;
                month?: string | null;
                county?: string | null;
                city?: string | null;
                zip?: string | null;
                subtype?: string | null;
                period?: "24" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_data_api_v1_map_get: {
        parameters: {
            query?: {
                version?: string | null;
                month?: string | null;
                county?: string | null;
                city?: string | null;
                zip?: string | null;
                subtype?: string | null;
                level?: "county" | "zip";
                metric?: "median_price" | "closed_sales" | "concentration";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    competitive_api_v1_competitive_get: {
        parameters: {
            query?: {
                version?: string | null;
                month?: string | null;
                county?: string | null;
                city?: string | null;
                zip?: string | null;
                subtype?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competitive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
