import {lazy,Suspense,useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowDownRight,ArrowUpRight,ArrowRight,ArrowLeft,SlidersHorizontal,RotateCcw,ChevronDown,Map,Info,Download} from 'lucide-react';
import type {EChartsOption} from 'echarts';
import {ApiError,get,useMarket,number,money,monthLabel,type Meta,type Selection,type Metrics,type Entity} from './api';
import {Chart,lineOption} from './Chart';
const MarketMap=lazy(()=>import('./MarketMap'));

const metricDefs=[{key:'median_price',label:'Median close price',color:'#bd632c',format:(n:number|null|undefined)=>money(n)},
 {key:'days_on_market',label:'Avg. days on market',color:'#bc5663',format:(n:number|null|undefined)=>n==null?'—':n.toFixed(1)+' days'},
 {key:'new_listings',label:'New listings',color:'#548751',format:number},
 {key:'closed_sales',label:'Closed sales',color:'#258187',format:number},
 {key:'price_ratio',label:'Close / original list price',color:'#916695',format:(n:number|null|undefined)=>n==null?'—':(n*100).toFixed(2)+'%'}] as const;
const filterKeys=['county','city','zip','subtype'] as const;
function readState():Selection{return Object.fromEntries(new URLSearchParams(location.search));}

export default function App(){
 const [state,setState]=useState<Selection>(readState);const [filtersOpen,setFiltersOpen]=useState(false);const [showMethods,setShowMethods]=useState(false);
 const client=useQueryClient();
 useEffect(()=>{const sync=()=>setState(readState());window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 function update(changes:Selection){const next={...state,...changes};Object.keys(next).forEach(k=>{if(!next[k])delete next[k];});history.pushState(null,'','?'+new URLSearchParams(next));setState(next);}
 const meta=useQuery({queryKey:['meta'],queryFn:({signal})=>get<Meta>('meta',{},signal),refetchInterval:300000});
 const month=state.month||meta.data?.end_month||'';const period=state.period==='all'?'all':'24';const tab=state.tab==='competitive'?'competitive':'trends';
 const level=state.level==='zip'?'zip':'county';const mapMetric=['closed_sales','concentration'].includes(state.metric)?state.metric:'median_price';
 const params:Selection={version:meta.data?.version||'',month,...Object.fromEntries(filterKeys.map(k=>[k,state[k]||'']))};
 const enabled=!!meta.data;const validPeriod=!!meta.data&&month>=meta.data.start_month&&month<=meta.data.end_month;
 const options=useMarket<'FilterOptions'>('filters',params,enabled&&validPeriod);
 const summary=useMarket<'Summary'>('summary',params,enabled&&validPeriod);
 const trends=useMarket<'Trends'>('trends',{...params,period},enabled&&validPeriod&&tab==='trends');
 const map=useMarket<'MapData'>('map',{...params,level,metric:mapMetric},enabled&&validPeriod);
 const competitive=useMarket<'Competitive'>('competitive',params,enabled&&validPeriod&&tab==='competitive');
 const error=meta.error||summary.error||map.error||(tab==='trends'?trends.error:competitive.error);
 const place=state.zip?`ZIP ${state.zip}`:state.city|| (state.county?state.county+' County':'California');
 const busy=summary.isFetching||map.isFetching;
 const [sortBy,setSortBy]=useState<'closed_sales'|'sales_volume'>('sales_volume');
 const [tableKind,setTableKind]=useState<'agents'|'offices'>('offices');
 const [page,setPage]=useState(0);
 useEffect(()=>setPage(0),[state.county,state.city,state.zip,state.subtype,month,tableKind,sortBy]);
 const compare=(key:keyof Metrics)=>{const current=summary.data?.current[key],prior=summary.data?.previous?.[key];if(current==null||prior==null||prior===0)return <span className="comparison">Previous month unavailable</span>;const change=(current-prior)/prior*100;return <span className="comparison">{change>=0?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(change).toFixed(1)}% <span>vs. previous month</span></span>;};
 function changeFilter(key:string,value:string){update({[key]:value,...(key==='county'?{city:'',zip:''}:key==='city'?{zip:''}:{})});}
 function refresh(){client.invalidateQueries();}
 const trendPoints=trends.data?.points||[];const labels=trendPoints.map(p=>monthLabel(p.month,true));
 const series=(key:keyof Metrics,color:string,format:(v:number)=>string)=>lineOption(labels,trendPoints.map(p=>p[key]??null),color,format);
 const trendRows=(key:keyof Metrics,format:(v:number|null)=>string)=>trendPoints.map(p=>[monthLabel(p.month),format(p[key]??null)]);
 const sortedEntities=[...(competitive.data?.[tableKind]||[])].sort((a,b)=>b[sortBy]-a[sortBy]);
 const ranking=(entities:Entity[],metric:'closed_sales'|'sales_volume',color:string):EChartsOption=>{const top=[...entities].sort((a,b)=>b[metric]-a[metric]).slice(0,8).reverse();return {grid:{left:155,right:65,top:8,bottom:25},tooltip:{trigger:'axis',axisPointer:{type:'shadow'}},xAxis:{type:'value',splitNumber:2,axisLabel:{hideOverlap:true,formatter:v=>metric==='sales_volume'?money(v,true):number(v),fontSize:10},splitLine:{lineStyle:{color:'#edf1f4'}}},yAxis:{type:'category',data:top.map(e=>e.name),axisLine:{show:false},axisTick:{show:false},axisLabel:{width:140,overflow:'truncate',fontSize:11}},series:[{type:'bar',data:top.map(e=>e[metric]),barMaxWidth:17,itemStyle:{color},label:{show:true,position:'right',formatter:p=>metric==='sales_volume'?money(Number(p.value),true):number(Number(p.value)),fontSize:10}}]};};
 const entityRows=(entities:Entity[])=>[...entities].sort((a,b)=>b.sales_volume-a.sales_volume).map(e=>[e.name,number(e.closed_sales),money(e.sales_volume),money(e.median_price)]);
 return <><a className="skip-link" href="#main">Skip to dashboard</a><header className="masthead"><div className="brand-mark"><Map size={24} strokeWidth={1.4}/></div><div><h1>California Housing Market Analysis</h1><p>Overview by Trenton Pham</p></div><div className="header-status"><span className="status-dot"/><span>Monthly market intelligence<small>{meta.data?'Updated '+new Date(meta.data.published_at).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Connecting to market data'}</small></span></div></header>
 {meta.data?.demo&&<div className="demo-banner"><Info size={15}/><strong>Demonstration dataset</strong><span>All prices, activity and rankings shown are synthetic.</span></div>}
 <main id="main"><div className="filter-toolbar"><button className="filter-toggle" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={16}/> Filter market <ChevronDown size={14}/></button><div className={'filters '+(filtersOpen?'open':'')}>
 {filterKeys.map((key,i)=>{const entries=options.data?.[(['counties','cities','zips','subtypes'] as const)[i]]||[];const label=['County','City','ZIP code','Property type'][i];return <label key={key}>{label}<select aria-label={label} value={state[key]||''} onChange={e=>changeFilter(key,e.target.value)}><option value="">{['All counties','All cities','All ZIP codes','All residential'][i]}</option>{state[key]&&!entries.includes(state[key])&&<option value={state[key]}>{state[key]} (no matches)</option>}{entries.map(value=><option key={value} value={value}>{value}</option>)}</select></label>;})}
 <button className="reset-button" onClick={()=>update({county:'',city:'',zip:'',subtype:''})}><RotateCcw size={14}/> Reset</button></div><label className="month-filter">Reporting month<select aria-label="Reporting month" value={month} onChange={e=>update({month:e.target.value})}>{!validPeriod&&month&&<option value={month}>{monthLabel(month)} · unavailable</option>}{meta.data?.months.slice().reverse().map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label></div>
 {meta.data&&!validPeriod&&<div role="alert" className="notice"><Info size={18}/><div><strong>This month is outside the available reporting period.</strong><p>Explore {monthLabel(meta.data.start_month)} through {monthLabel(meta.data.end_month)}.</p></div><button onClick={()=>update({month:month<meta.data!.start_month?meta.data!.start_month:meta.data!.end_month})}>Use nearest available month <ArrowRight size={14}/></button></div>}
 {error&&<div role="alert" className="notice"><Info size={18}/><div><strong>{error.message}</strong><p>Your selected filters are preserved.</p></div><button onClick={refresh}>{error instanceof ApiError&&error.status===409?'Load current dataset':'Try again'}</button></div>}
 <section className="overview" aria-busy={busy}><div className="map-panel"><div className="panel-top"><div><h2>Explore the market</h2><p>Select an area to see its market in focus.</p></div><div className="map-controls"><select aria-label="Map metric" value={mapMetric} onChange={e=>update({metric:e.target.value})}><option value="median_price">Median close price</option><option value="closed_sales">Closed sales</option><option value="concentration">Sales concentration</option></select><div className="segmented" aria-label="Map geography"><button aria-pressed={level==='county'} onClick={()=>update({level:'county'})}>County</button><button aria-pressed={level==='zip'} onClick={()=>update({level:'zip'})}>ZIP</button></div></div></div><Suspense fallback={<div className="map-frame skeleton"/>}><MarketMap data={validPeriod?map.data:undefined} selected={state[level]||''} onSelect={value=>changeFilter(level,value)}/></Suspense>
 <div className="map-footnote"><span>{level==='zip'?'ZIP areas use approximate Census ZCTA boundaries.':'California residential properties · CRMLS coverage'}</span><details><summary>Map data</summary><div className="table-scroll"><table><thead><tr><th>Area</th><th>Median price</th><th>Closed sales</th></tr></thead><tbody>{map.data?.areas.map(a=><tr key={a.id}><td><button onClick={()=>changeFilter(level,a.id)}>{a.name}</button></td><td>{money(a.median_price)}</td><td>{number(a.closed_sales)}</td></tr>)}</tbody></table></div></details></div></div>
 <aside className="area-summary"><div className="summary-title"><h2>{place}</h2><p>{month?monthLabel(month):'Loading reporting period'}{state.subtype?' · '+state.subtype:' · All residential'}</p></div><div className="summary-metrics">{metricDefs.map((metric,i)=><div key={metric.key} className={'summary-metric '+(i===0?'primary-metric':'')}><span className="metric-label">{metric.label}</span><strong style={i===0?{color:'#23496b'}:undefined}>{summary.data&&validPeriod?metric.format(summary.data.current[metric.key]):'—'}</strong>{compare(metric.key)}</div>)}</div><button className="method-link" onClick={()=>setShowMethods(!showMethods)} aria-expanded={showMethods}><Info size={14}/> How these metrics are calculated</button></aside></section>
 {showMethods&&<section className="methodology"><h2>About the data</h2><p>New listings follow listing-contract month; closed sales follow close month. Medians are calculated from individual qualifying sales. Days on market and price per square foot exclude invalid values. The historical three-IQR price filter and 75–150% close-to-original-price rule define the sold cohort. Comparisons use the previous month with the same filters.</p><p>Mortgage rates are monthly averages of weekly national Freddie Mac observations from FRED. They do not change with geography. Charts show available CRMLS coverage, not every California transaction. The database retains up to 36 completed months and refreshes on the seventh each month.</p></section>}
 <div className="tab-bar" role="tablist" aria-label="Analysis"><button id="trends-tab" role="tab" aria-selected={tab==='trends'} aria-controls="analysis-panel" tabIndex={tab==='trends'?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){update({tab:'competitive'});document.getElementById('competitive-tab')?.focus();}}} onClick={()=>update({tab:'trends'})}>Market Trends</button><button id="competitive-tab" role="tab" aria-selected={tab==='competitive'} aria-controls="analysis-panel" tabIndex={tab==='competitive'?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){update({tab:'trends'});document.getElementById('trends-tab')?.focus();}}} onClick={()=>update({tab:'competitive'})}>Competitive Analysis</button><span className="tab-context">{place}{busy?' · Updating…':''}</span></div>
 <section id="analysis-panel" role="tabpanel" aria-labelledby={tab+'-tab'}>
 {tab==='trends'?<><div className="section-heading"><div><h2>The market, over time</h2><p>Monthly movement in prices, activity and the pace of sales.</p></div><div className="segmented"><button aria-pressed={period==='24'} onClick={()=>update({period:'24'})}>24 months</button><button aria-pressed={period==='all'} onClick={()=>update({period:'all'})}>All available</button></div></div>{trends.isLoading?<div className="loading-state" role="status">Loading market trends…</div>:<div className="chart-grid">
 <Chart tall title="Home prices & mortgage rates" description="Aligned monthly trends · separate price and rate scales" option={{tooltip:{trigger:'axis'},axisPointer:{link:[{xAxisIndex:'all'}]},grid:[{left:76,right:20,top:40,height:'34%'},{left:76,right:20,top:'62%',bottom:38}],xAxis:[{type:'category',gridIndex:0,data:labels,boundaryGap:false,axisLabel:{show:false},axisTick:{show:false}},{type:'category',gridIndex:1,data:labels,boundaryGap:false,axisLabel:{fontSize:11,hideOverlap:true},axisTick:{show:false}}],yAxis:[{type:'value',gridIndex:0,scale:true,name:'Median close price ($)',nameLocation:'end',nameTextStyle:{align:'left'},splitNumber:4,axisLabel:{formatter:(v:number)=>money(v,true),fontSize:11},splitLine:{lineStyle:{color:'#edf1f4'}}},{type:'value',gridIndex:1,scale:true,name:'30-year mortgage rate (%)',nameLocation:'end',nameTextStyle:{align:'left'},splitNumber:4,axisLabel:{formatter:(v:number)=>v.toFixed(1)+'%',fontSize:11},splitLine:{lineStyle:{color:'#edf1f4'}}}],series:[{name:'Median close price',type:'line',xAxisIndex:0,yAxisIndex:0,data:trendPoints.map(p=>p.median_price),showSymbol:false,lineStyle:{color:'#c26d35',width:2.5},itemStyle:{color:'#c26d35'},areaStyle:{color:'#c26d35',opacity:0.06}},{name:'National mortgage rate',type:'line',xAxisIndex:1,yAxisIndex:1,data:trendPoints.map(p=>p.mortgage_rate),showSymbol:false,lineStyle:{color:'#4778aa',width:2.5},itemStyle:{color:'#4778aa'},areaStyle:{color:'#4778aa',opacity:0.06}}]}} columns={['Month','Median close price','National mortgage rate']} rows={trendPoints.map(p=>[monthLabel(p.month),money(p.median_price),p.mortgage_rate==null?'—':p.mortgage_rate.toFixed(2)+'%'])}/>
 <Chart title="New listings & closed sales" description="Supply entering the market and completed transactions" option={{...lineOption(labels,trendPoints.map(p=>p.new_listings),'#548751',number),legend:{top:0,right:10,data:['New listings','Closed sales'],textStyle:{fontSize:11}},grid:{left:58,right:20,top:38,bottom:38},series:[{name:'New listings',type:'line',data:trendPoints.map(p=>p.new_listings),showSymbol:false,lineStyle:{color:'#548751',width:2.5},itemStyle:{color:'#548751'}},{name:'Closed sales',type:'line',data:trendPoints.map(p=>p.closed_sales),showSymbol:false,lineStyle:{color:'#258187',width:2.5,type:'dashed'},itemStyle:{color:'#258187'}}]}} columns={['Month','New listings','Closed sales']} rows={trendPoints.map(p=>[monthLabel(p.month),number(p.new_listings),number(p.closed_sales)])}/>
 <Chart title="Average price per square foot" description="Average of valid individual sale ratios" option={series('price_sqft','#9a775e',v=>money(v))} columns={['Month','Price / sq ft']} rows={trendRows('price_sqft',v=>money(v))}/>
 <Chart title="Average days on market" description="Time on market for qualifying closed sales" option={series('days_on_market','#bc5663',v=>v.toFixed(0)+' d')} columns={['Month','Average days']} rows={trendRows('days_on_market',v=>v==null?'—':v.toFixed(1))}/>
 <Chart title="Close-to-original-list-price ratio" description="100% means the home sold at its original asking price" option={series('price_ratio','#916695',v=>(v*100).toFixed(2)+'%')} columns={['Month','Price ratio']} rows={trendRows('price_ratio',v=>v==null?'—':(v*100).toFixed(2)+'%')}/>
 </div>}</>:<><div className="section-heading"><div><h2>Who is moving the market</h2><p>Listing-side performance in {place} · {month&&monthLabel(month)}</p></div></div>{competitive.isLoading?<div className="loading-state" role="status">Loading competitive analysis…</div>:<><div className="chart-grid">{(['agents','offices'] as const).flatMap(kind=>(['closed_sales','sales_volume'] as const).map(metric=><Chart key={kind+metric} title={`Top ${kind} by ${metric==='closed_sales'?'properties sold':'sales volume'}`} option={ranking(competitive.data?.[kind]||[],metric,kind==='agents'?'#4778aa':'#916695')} columns={['Name','Properties sold','Sales volume','Median price']} rows={entityRows(competitive.data?.[kind]||[])}/>))}
 <Chart title="Brokerage market position" description="Sales count × median price · bubble size represents volume" option={{grid:{left:65,right:25,top:20,bottom:40},tooltip:{formatter:p=>{const item=(p as {data?:{name?:string}}).data;return item?.name||'';}},xAxis:{name:'Closed sales',nameLocation:'middle',nameGap:26,splitLine:{lineStyle:{color:'#edf1f4'}}},yAxis:{axisLabel:{formatter:(v:number)=>money(v,true)},splitLine:{lineStyle:{color:'#edf1f4'}}},series:[{type:'scatter',data:(competitive.data?.offices||[]).map(e=>({name:e.name,value:[e.closed_sales,e.median_price,e.sales_volume]})),symbolSize:(v:number[])=>Math.max(7,Math.min(55,Math.sqrt(v[2])/300)),itemStyle:{color:'#916695',opacity:0.7}}]}} columns={['Brokerage','Properties sold','Sales volume','Median price']} rows={entityRows(competitive.data?.offices||[])}/>
 <Chart title="Brokerage market share" description="Share of total qualifying sales volume" option={{tooltip:{formatter:p=>{const d=(p as {data?:{name?:string;value?:number}}).data;return `${d?.name||''}: ${money(d?.value)}`;}},series:[{type:'treemap',roam:false,nodeClick:false,breadcrumb:{show:false},left:0,right:0,top:8,bottom:5,leafDepth:1,label:{show:true,fontSize:12,overflow:'truncate',color:'#ffffff'},itemStyle:{borderColor:'#fff',borderWidth:2,gapWidth:2},color:['#23496b','#39718a','#538b9c','#659fa9','#75b0b4','#83bbc0','#528392','#456b7e'],data:(competitive.data?.offices||[]).map((e,i)=>({name:e.name,value:e.sales_volume,itemStyle:{color:['#23496b','#305d78','#386d7e','#3b7179','#3e6675','#405e73','#326773','#3e5b6e'][i%8]}}))}]}} columns={['Brokerage','Market share','Sales volume']} rows={(competitive.data?.offices||[]).map(e=>[e.name,(e.market_share*100).toFixed(2)+'%',money(e.sales_volume)])}/>
 </div><section className="rankings-table"><div className="section-heading"><h3>Explore the rankings</h3><div className="table-controls"><select aria-label="Ranking group" value={tableKind} onChange={e=>setTableKind(e.target.value as 'agents'|'offices')}><option value="offices">Brokerages</option><option value="agents">Agents</option></select><button className="quiet-button" onClick={()=>{const data=[['Name','Properties sold','Sales volume','Median price'],...entityRows(sortedEntities)].map(r=>r.map(v=>'"'+String(v).replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`market-rankings-${month}.csv`;a.click();URL.revokeObjectURL(url);}}><Download size={14}/> Export table</button></div></div><div className="table-scroll"><table><thead><tr><th scope="col">{tableKind==='offices'?'Brokerage':'Agent'}</th><th scope="col"><button onClick={()=>setSortBy('closed_sales')}>Properties sold {sortBy==='closed_sales'?'↓':''}</button></th><th scope="col"><button onClick={()=>setSortBy('sales_volume')}>Sales volume {sortBy==='sales_volume'?'↓':''}</button></th><th scope="col">Median price</th><th scope="col">Volume share</th></tr></thead><tbody>{sortedEntities.slice(page*10,page*10+10).map(e=><tr key={e.id}><td>{e.name}</td><td>{number(e.closed_sales)}</td><td>{money(e.sales_volume)}</td><td>{money(e.median_price)}</td><td>{(e.market_share*100).toFixed(2)}%</td></tr>)}</tbody></table></div><div className="pagination"><span>{number(sortedEntities.length)} {tableKind}</span><button disabled={page===0} aria-label="Previous ranking page" onClick={()=>setPage(page-1)}><ArrowLeft size={16}/></button><span>Page {page+1} of {Math.max(1,Math.ceil(sortedEntities.length/10))}</span><button disabled={(page+1)*10>=sortedEntities.length} aria-label="Next ranking page" onClick={()=>setPage(page+1)}><ArrowRight size={16}/></button></div></section></>}</>}
 </section><footer><span>California Housing Market Analysis <span className="footer-divider">/</span> Trenton Pham</span><p>{meta.data?.source||'CRMLS via Trestle'} · <a href="https://fred.stlouisfed.org/series/MORTGAGE30US" target="_blank" rel="noreferrer">Freddie Mac / FRED</a> · US Census Bureau</p><small>{meta.data?`${monthLabel(meta.data.start_month)}–${monthLabel(meta.data.end_month)} · `:''}Up to 36 completed months · Refreshed on the seventh</small></footer>
 </main></>;
}
